FROM debian:stretch
MAINTAINER Miguel Sanches <miguel-r-sanches@telecom.pt>

RUN apt-get update && \
    apt-get install -q -y \
        gnupg \
        wget \
        curl \
        ca-certificates \
        apt-transport-https && \
    wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add - && \
    echo "deb https://packages.sury.org/php/ stretch main" | tee /etc/apt/sources.list.d/php.list && \
    apt-get update && \
    apt-get -q -y install \
        nginx \
        openssl \
        php7.2 \
        php7.2-cli \
        php7.2-common \
        php7.2-curl \
        php7.2-mbstring \
        php7.2-xml \
        php7.2-json \
        php7.2-bcmath \
        php7.2-fpm \
        php7.2-gd \
        php7.2-sqlite

COPY --chown=www-data:www-data ./site /site
COPY --chown=www-data:www-data ./www.conf /etc/php/7.2/fpm/pool.d

RUN mkdir /run/php

WORKDIR /site

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    mv composer.phar /usr/local/bin/composer && \
    composer install --optimize-autoloader --no-dev && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get -q -y install nodejs && \
    npm install
