#
# Node build
#
FROM node:10-stretch as frontend

COPY ./site /site

WORKDIR /site
RUN npm install
RUN npm run prod

#
# Webserver
#
FROM nginx:1.13-alpine

COPY --chown=www-data:www-data  ./site /site
COPY --chown=www-data:www-data  ./docker/default.conf /etc/nginx/conf.d/default.conf

COPY --from=frontend --chown=www-data:www-data /site/public/js/ /site/public/js/
COPY --from=frontend --chown=www-data:www-data /site/public/css/ /site/public/css/
COPY --from=frontend --chown=www-data:www-data /site/public/mix-manifest.json /site/public/mix-manifest.json
