version: '2'
services:
  nginx:
    image: 'nginx:1.13-alpine'
    ports:
      - '8088:80' #Site port
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - './site:/site'
    depends_on:
      - site
  site:
    build:
      context: .
      dockerfile: Dockerfile-php-site-local
    command: php-fpm7.2 -F -R
    volumes:
      - './site:/site'
    depends_on:
      - cache
  cache:
      image: 'redis:4.0-alpine'
      ports:
        - '6379:6379'